development:
  adapter: mysql2
  encoding: utf8
  database: timetable
  username: root
  password: abm20h

production:
  adapter: mysql2
  encoding: utf8
  database: timetable
  username: root
  password:
